language: cpp

compiler:
  - gcc

env:
  global:
    - secure: "Wr0gQ1pO0fGEaNputmL0W4Nl4FKwTRlonqPdNIBWsD2kWaRDrgpbkWKcpdcOFL8E9/DjW35bxLZR7y3C/JBe2yAm8HUc4t4Px2JIOCFlCIC4UyQSftbV3uZLBq6kmP6/gokVBmMXFKEfuRsMEQ6joWJb15T1fRQQ43fgO+1PUVE="

addons:
  coverity_scan:
    project:
      name: "mbehr1/faulty_code"
    notification_email: mbehr@mcbehr.de
    build_command_prepend: "cmake ."
    build_command:   "make"
    branch_pattern: coverity_scan

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - cmake . && make && make test
